<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>dev.bpm-crafters.process-engine-api-testing</groupId>
    <artifactId>process-engine-api-testing-root</artifactId>
    <version>2026.10.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>process-engine-api-testing-bom</artifactId>
  <name>Process Engine API Testing BOM</name>
  <description>BOM of Process Engine API Testing</description>
  <packaging>pom</packaging>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>dev.bpm-crafters.process-engine-api-testing</groupId>
        <artifactId>process-engine-api-testing-core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.bpm-crafters.process-engine-api-testing</groupId>
        <artifactId>process-engine-api-testing-jgiven</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
